package roboticoffee.utils;

public enum TokenType {
    NUMBER, IDENTIFIER, OPERATOR, KEYWORD, OPEN_PAREN, CLOSE_PAREN, OPEN_BRACE, CLOSE_BRACE, OPEN_BRACKET, CLOSE_BRACKET, SEMICOLON, UNKNOWN
}
