package roboticoffee.utils;

public enum TokenType {
    NUMBER, STRING, BOOLEAN, IDENTIFIER, OPERATOR, KEYWORD, OPEN_PAREN, CLOSE_PAREN, OPEN_BRACE, CLOSE_BRACE, OPEN_BRACKET, CLOSE_BRACKET, SEMICOLON, UNKNOWN, COMMA
}
